config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#top'
  
  resources :feeds
  resources :contacts
  
  get '/top', to: 'blogs#top'
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :users
  resources :sessions
  resources :favorites, only:[:create, :destroy]
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true, length: {in: 1..140}
  validates :content, presence: true, length: {in: 1..140}
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :login_check, only: [:new, :edit, :update, :destroy, :show]
  
  def top
  end
  
  def index
    @blog = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    
    if @blog.save
      ContactMailer.blog_mail(current_user).deliver 
      redirect_to blogs_path
    else
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path
  end
  
  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end
  
  private
  
  def blog_params
    params.require(:blog).permit(:title, :content, :user_id, :image, :image_cache)
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
 
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %> errors</h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  
  <div>
    <%= image_tag(@blog.image.url) if @blog.image.url %>
    <%= form.file_field :image %> 
    <%= form.hidden_field :image_cache %>
  </div>
  
  <%= form.submit class: 'button' %>
<% end %>

<%= link_to 'back', blogs_path, class: 'button' %>

app/views/blogs/confirm.html.erb
<h3>Send as follows:</h3>
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  
  <%= image_tag(@blog.image.url) %>
  <p>title : <%=@blog.title%></p>
  <p>content : <%=@blog.content%></p>
  <%= form.submit "submit", class: 'button' %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit 'back', name: 'back', class: 'button' %>
<% end %>

app/views/blogs/edit.html.erb
<h1>edit Blogs</h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<div class="container">
  <h1>Blogs</h1>

    
    <% @blog.each do |blog| %>
    
    <div class="blog_box col-md-6">
      <ul class="row">
        <li class="col-md-1 col-xs-1 workbreak"><%= blog.title %></li>
        <li class="col-md-5 col-xs-3 workbreak"><%= blog.content %></li>
        <li class="col-md-1 col-xs-1 workbreak"><%= blog.user.name %></li>
        <li class="col-md-1 col-xs-2"><%= link_to 'show', blog_path(blog.id), class: 'button' %></li>
        <% if defined?(current_user.id) %>
          <% if blog.user_id == current_user.id %>
            <li class="col-md-1 col-xs-2"><%= link_to 'edit', edit_blog_path(blog.id), class: 'button' %></li>
            <li class="col-md-1 col-xs-2"><%= link_to 'delete', blog_path(blog.id), method: :delete, class: 'button' %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <% end %>
    <ul class="row">
      <li class="col-md-12 col-xs-12"><%= link_to 'new', new_blog_path, class: 'button' %></li>
    </ul>
    
  
</div>

app/views/blogs/new.html.erb
<h1>New Blogs</h1>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>Show Blogs</h1>

<p>
  <%= image_tag @blog.image.url if @blog.image.url %>
</p>

<p>title : <%= @blog.title %></p>
<p>content : <%= @blog.content %></p>

<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to 'back', blogs_path, class: 'button' %>

app/views/blogs/top.html.erb
<div class="container top_box">
  <div class="row top">
    <div class="img_box col-md-12 col-xs-12">
      <%= image_tag ('Blog_icon.png')%>
    </div>
  </div>
  <ul class="row blogs_path">
    <li class="col-md-12 col-xs-12"><%= link_to 'Go to Blog', blogs_path, class: 'button' %></li>
    <li class="col-md-12 col-xs-12">このアプリはブログにbootstrapを導入したアプリです。</li>
  </ul>
</div>