config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#top'
  
  resources :feeds
  resources :contacts
  
  get '/top', to: 'blogs#top'
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :users
  resources :sessions
  resources :favorites, only:[:create, :destroy]
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation{email.downcase!}
  has_secure_password
  validates :password, presence: true, length: {minimum: 3}
  has_many :blogs
  
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  mount_uploader :image, ImageUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  
  def show 
    @favorites_blogs = @user.favorite_blogs
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_image)
      redirect_to user_path
    else
      render 'edit'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:image, :image_cache)
  end
  
  def user_image
    params.require(:user).permit(:image, :image_cache)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true, url: user_path) do |form| %>
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %> errors</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= image_tag(@user.image.url) if @user.image.url %>
    <%= form.file_field :image %> 
    <%= form.hidden_field :image_cache %>
  </div>
  <%= form.submit class: 'button' %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  
  <div>
    <%= image_tag(@user.image.url) if @user.image.url %>
    <%= f.file_field :image %> 
    <%= f.hidden_field :image_cache %>
  </div>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %> page </h1>
<p>emails : <%= @user.email %></p>



<br>

  <%= image_tag @user.image.url if @user.image.url%>



<% @favorites_blogs.each do |favorites_blogs| %>
  <div class="blog_box col-md-6">
    <ul class="row">
      <li class="col-md-1 col-xs-1 workbreak"><%= favorites_blogs.title %></li>
      <li class="col-md-5 col-xs-3 workbreak"><%= favorites_blogs.content %></li>
      <li class="col-md-1 col-xs-1 workbreak"><%= favorites_blogs.user.name %></li>
      <li class="col-md-1 col-xs-2"><%= link_to 'show', blog_path(favorites_blogs.id), class: 'button' %></li>
      <% if defined?(current_user.id) %>
        <% if favorites_blogs.user_id == current_user.id %>
          <li class="col-md-1 col-xs-2"><%= link_to 'edit', edit_blog_path(favorites_blogs.id), class: 'button' %></li>
          <li class="col-md-1 col-xs-2"><%= link_to 'delete', blog_path(favorites_blogs.id), method: :delete, class: 'button' %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>